# ACTIONS REQUIRED: Replace YOUR_NAMESPACE_HERE with your namespace.
# ACTIONS REQUIRED: Replace YOUR_REPO_IMAGE_HERE with the name of your built image.
#
# This file defines the ClusterServiceVersion (CSV) to tell the catalog how to display, create and
# manage the application as a whole. If changes are made to the CRD for this application kind,
# make sure to replace those references below as well.
apiVersion: app.coreos.com/v1alpha1
kind: ClusterServiceVersion-v1
metadata:
  name: example-app-operator.v0.0.1
  namespace: YOUR_NAMESPACE_HERE
spec:
  install: 
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: example-app-operator
        rules:
        - apiGroups:
          - example.com
          resources:
          - example-apps
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - events
          - namespaces
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - "namespaces"
          verbs:
          - "get"
        - apiGroups:
          - apps
          - extensions
          resources:
          - deployments
          verbs:
          - "*"
      deployments: 
      - name: example-app-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: example-app-operator
          template:
            metadata:
              labels:
                app: example-app-operator
            spec:
              containers:
                - name: sao
                  image: YOUR_REPO_IMAGE_HERE
                  ports:
                    - containerPort: 8080
                      protocol: TCP
                  imagePullPolicy: Always
              restartPolicy: Always
              terminationGracePeriodSeconds: 5
              serviceAccountName: example-app-operator
              serviceAccount: example-app-operator
  customresourcedefinitions:
    owned:
      - description: Represents a cluster of example apps
        displayName: Example App
        kind: ExampleApp
        name: example-apps.example.com
        version: v1alpha1
        resources:
          - kind: Deployment
            version: v1beta2
          - kind: ReplicaSet
            version: v1beta2
          - kind: Pod
            version: v1
        specDescriptors:
          - description: The desired number of member Pods for the deployment.
            displayName: Size
            path: size
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:podCount'
        statusDescriptors:
          - description: The current status of the application.
            displayName: Status
            path: phase
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase'
          - description: Explanation for the current status of the application.
            displayName: Status Details
            path: reason
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase:reason'
  keywords:
    - example
    - app
  displayName: Example Application
  provider:
    name: Example Corp
    url: www.example.com
  maturity: alpha
  version: 0.0.1
  maintainers:
    - email: corp@example.com
      name: Some Corp
  description: Main enterprise application providing business critical features with high availabilty and no manual intervention.
  labels:
    alm-owner-enterprise-app: example-app-operator
    alm-status-descriptors: example-app-operator.v0.0.1
